### ISSUE TITLE
coupons_controller_spec.rb has inconsistent params as rest of lab

### ISSUE THREAD

**Issue by rh24** [learn-co-curriculum/rails-index-show-new-create-lab#13]
Passing in the params hash in lines 9 and 14 as a nested hash ` { :coupon => { :coupon_code => "ASD123", :store => "Dean and Deluca" } }` is inconsistent with the way the params are being created in the views in the solution code.

Changing the spec in lines 9 and 14 to `{ :coupon_code => "ASD123", :store => "Dean and Deluca" }` fixes this issue.

**Comment by realAndrewCohn** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved by #9 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
