### ISSUE TITLE
Some tests want the coupon code to be the link; others want the store to be the link.

### ISSUE THREAD

**Issue by Anw0514** [learn-co-curriculum/rails-index-show-new-create-lab#15]

**Comment by darrendaz** [comment]
I ended up giving the tests what they really wanted...both forms of the link on the same page pointing to the same path and now it's passing.

**Comment by drakeltheryuujin** [comment]
The link should be the coupon code and the store should not be linked. We've updated the materials to make this more clear. Thanks for your contribution!

**Comment by mkirby** [comment]
@drakeltheryuujin the test _Multiple coupons are shown_ expects the store name as the link, while the test _linking from the index page to the show page_ expects the coupon_code to be the link. I believe that is the issue that still persists. 

Expects coupon.store as the link
```
describe 'Multiple coupons are shown' do
  it 'on the index page' do
    Coupon.create(coupon_code: "ASD123", store: "Chipotle")
    Coupon.create(coupon_code: "XYZ098", store: "Jamba")
    visit coupons_path
    expect(page).to have_content(/Chipotle|Jamba/)
  end
end
```
expects coupon.coupon_code as the link
```
describe 'linking from the index page to the show page' do
  it 'index page coupon code text is hyperlinked to coupon page' do
    linked_coupon = Coupon.create(coupon_code: "FREESTUFF", store: "Chipotle")
    visit coupons_path
    expect(page).to have_link(linked_coupon.coupon_code, href: coupon_path(linked_coupon))
  end
end
```
