### ISSUE TITLE
Two conflicting tests for the index page

### ISSUE THREAD

**Issue by mkirby** [learn-co-curriculum/rails-index-show-new-create-lab#28]
The test Multiple coupons are shown expects the store name as the link, while the test linking from the index page to the show page expects the coupon_code to be the link. It seems this issue still persists.

Expects coupon.store as the link
```
describe 'Multiple coupons are shown' do
  it 'on the index page' do
    Coupon.create(coupon_code: "ASD123", store: "Chipotle")
    Coupon.create(coupon_code: "XYZ098", store: "Jamba")
    visit coupons_path
    expect(page).to have_content(/Chipotle|Jamba/)
  end
end
```
expects coupon.coupon_code as the link
```
describe 'linking from the index page to the show page' do
  it 'index page coupon code text is hyperlinked to coupon page' do
    linked_coupon = Coupon.create(coupon_code: "FREESTUFF", store: "Chipotle")
    visit coupons_path
    expect(page).to have_link(linked_coupon.coupon_code, href: coupon_path(linked_coupon))
  end
end
```

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been addressed.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
