### ISSUE TITLE
Lab is missing config/secrets-template.yml

### ISSUE THREAD

**Issue by gormanjp** [learn-co-curriculum/rails-index-show-new-create-lab#6]
The template for the secrets.yml file doesn't seem to be included in the repo.

**Comment by aturkewi** [comment]
@pletcher @PeterBell 
Hey guys, some how the readme got deployed to Learn, so students see the paragraph _about_ the secrets.yml file, but when they fork and clone, the -v-000 deploy does not have the secrests_template.yml or the updated readme.

**Comment by pletcher** [comment]
Redeployed, looks like it's fixed now.
